### ISSUE TITLE
Fix ambiguity in LineaStateBridge

### ISSUE THREAD

**Issue by kfastov** [kfastov/world-id-state-bridge-linea#34]
`transferOwnership` method that initiates ownership transfer in Linea has the same name as "normal" transferOwnership from `Ownable2Step`. It's better to rename it back to `transferOwnershipLinea`.

Don't forget to update all mentions in tests and scripts

**Comment by ikemHood** [comment]
Hey @kfastov I'd like to implement this

**Comment by Iwueseiter** [comment]
Hi @kfastov can I work on this?

**Comment by adrianvrj** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-bridge-linea).

### My background and how it can be leveraged
Hi, my name is Adrian, I have experience with solidity and have worked in some projects using this language

### How I plan on tackling this issue
 I will rename the method and check all the mentions in code making sure to rename them. Then I would run the tests to make sure everything is fine.

**Comment by EmmanuelAR** [comment]
heyy @kfastov can i work on this? 

i will...

1. Communicate with Your Team:

	•	Notify your team about the need to rename the transferOwnership method in the Linea contract to transferOwnershipLinea to avoid conflicts with Ownable2Step.
	•	Ensure they are aware that all mentions of this method in tests and scripts will need to be updated accordingly.

2. Update Documentation:

	•	Document this change in your project’s documentation, specifying that transferOwnership in Linea has been renamed to transferOwnershipLinea.
	•	Include instructions on where this change needs to be reflected (e.g., in tests, deployment scripts, etc.).

3. Coordinate with QA/Testing:

	•	Inform the QA team to update and verify all test cases that involve transferOwnership to ensure they now refer to transferOwnershipLinea.

4. Schedule the Change:

	•	Set a timeline or schedule for implementing this change, ensuring that all dependent code is updated simultaneously to avoid any disruption.
